### ISSUE TITLE
Type Filter Selection - Apply Filters Button

### ISSUE THREAD

**Issue by Mohammedks713** [FightPandemics/FightPandemics-iOS#140]
NOTE: This is ONLY for the Apply Filters portion of the UI - NOT the Type title, the - button, the Type Tags, or the Clear Filters button

- Pill button with dark theme
- Inactive if no Filters applied
- Becomes active if any Filters are applied
-  Returns to inactive state if all Filters manually removed
-  Returns to inactive state if "Clear filters" button is tapped
-  If active and tapped, applies Filter selection globally
-  Localized

![image](https://user-images.githubusercontent.com/51894843/82605476-fd3ee500-9b83-11ea-8969-e1acc7b31395.png)

**Comment by ethanswift** [comment]
Is this exactly identical to the location's apply filter or it also takes the number of filters applied?

**Comment by devarshjoshi** [comment]
same as #96, can be closed. @ethanswift
