### ISSUE TITLE
Type Filters Selection - Clear Filters Button

### ISSUE THREAD

**Issue by Mohammedks713** [FightPandemics/FightPandemics-iOS#141]
NOTE: This is ONLY for the Clear Filters portion of the UI - NOT the Type title, the - button, the Tags, or the Apply filters button

Pill button with light theme
Upon tapping -  clears Type selection (if made) and inactivates tags
Localized

![image](https://user-images.githubusercontent.com/51894843/82607929-beab2980-9b87-11ea-9ed2-395a4f609ded.png)

**Comment by devarshjoshi** [comment]
closing as duplicate of #127
