### ISSUE TITLE
Feed Filter From Whom - Clear Filter

### ISSUE THREAD

**Issue by Mohammedks713** [FightPandemics/FightPandemics-iOS#144]
NOTE: This is ONLY for the Clear Filters portion of the UI - NOT the From whom title, the - button, the Tags, or the Apply filters button

- Pill button with light theme
- Upon tapping - closes From Whom (if open); clears Tag selection (if made)
- Localized

**Comment by devarshjoshi** [comment]
Closing this as it is duplicate of #127
