### ISSUE TITLE
Feed/Offer-Request Card - Heart Button

### ISSUE THREAD

**Issue by Mohammedks713** [FightPandemics/FightPandemics-iOS#150]
Note: This refers only to the Like button on the card and the text accompanying it

- The like Button will be inactive by default and activate when clicked, changing color to be filled in

- The number of likes to the right will update to reflect the additional like from the user

![image](https://user-images.githubusercontent.com/51894843/82616226-a09af480-9b9a-11ea-813d-1916c077963a.png)

**Comment by ethanswift** [comment]
@devarshjoshi , @OnyekachiSamuel  has already been worked on, close the issue.
