### ISSUE TITLE
Feed Filter

### ISSUE THREAD

**Issue by devarshjoshi** [FightPandemics/FightPandemics-iOS#22]
https://www.notion.so/fightpandemics/Filters-for-the-Feed-9889702415454f65b8e137e58b8458f4
prototype: https://staging.fightpandemics.work/ - click on view community postings on the bottom

Given: When a user is on the feed page
When: user clicks on the location button
Then: A popup should appear from the bottom with a location field and button to use current location
and when: the user enters the zip code and clicks on apply
then the popup should close and the results displayed

And 
When: User select the "From Whom" button 
Then: A popup should appear from the bottom with the options of personas 

And When User selects the "Type"
then: the popup should appear with the different types of help available
 
And When User selects the "Need or Give Help"
then: the popup should appear with the need or give help button selected

And When user selects the location button
then the user should see an option to allow use of location if they havent already

Notes: 
User should be able to select multiple personas, need or give help button, and from whom buttons

**Comment by haidalinda** [comment]
will be revisited with new mobile designs - feel free to re-open if im incorrect
