### ISSUE TITLE
Symptom Checker- Shrink size of multiple choice on Questions 2,3,and 6

### ISSUE THREAD

**Issue by vikjoshi** [FightPandemics/FightPandemics-iOS#42]
Summary: For the multiple choice questions 2,3,6 on the Symptom Checker, can we reduce the size of the options so they can fit on one page without needing to scroll down so we don't lose valuable real estate? 

STR: Enter Symptom Checker and go to Question 2 (or 3 or 6)

Expected Results: All choices should be seen without needing to scroll down
Actual Result: Need to scroll down to see all choices
Device:iPhone XS

See attached screenshot
![IMG-1333](https://user-images.githubusercontent.com/41554004/81759711-48694180-947a-11ea-8522-97e37a07799d.PNG)

**Comment by stavares843** [comment]
this needs to be reported on https://github.com/FightPandemics/FightPandemics/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by vikjoshi** [comment]
Will do, thanks @stavares843
