### ISSUE TITLE
Reusable Full-screen Alert UI

### ISSUE THREAD

**Issue by haidalinda** [FightPandemics/FightPandemics-iOS#51]
Create a reusable component we'll call "Search Bar". It should:

* Slide up from the bottom of the screen
* Have a content area of a configurable height that includes a Pill Button

Additionally:

* The background behind the bottom modal should be gray with an opacity
* The background should fade in
* Upon tapping the background, the alert should be dismissed
* Upon tapping the Pill Button, the alert should be dismissed
* Dismissal should slide the alert down and fade out the background

**Design**
Check on the screenshot below
[Link to Design](https://www.figma.com/file/4cV84H1jyMo0rJEAl3HNnJ/FightPandemics-landing-page?node-id=6638%3A29348)

**EXAMPLES**:

![Screen Shot 2020-05-13 at 9 45 40 PM](https://user-images.githubusercontent.com/5456481/81883471-4fb84a00-9563-11ea-924f-3b4e456d99f2.png)

![Screen Shot 2020-05-13 at 9 45 51 PM](https://user-images.githubusercontent.com/5456481/81883477-53e46780-9563-11ea-8565-8d8fea18be9a.png)

**Comment by ethanswift** [comment]
I think you made mistake in images. This should be search bar image not Alert UI image
