### ISSUE TITLE
Post creation - visibility selection 

### ISSUE THREAD

**Issue by helenebar** [FightPandemics/FightPandemics-iOS#62]
**AS** a user,
**Given** that I am on the "create a post" page
**When** I tap on "share with anyone" dropdown menu
**Then** a pop up appears with 4 options: My neighborhood; My city; My country; Anyone

**Design**
<img width="244" alt="Capture d’écran 2020-05-14 à 17 21 45" src="https://user-images.githubusercontent.com/65354126/81959542-85af0a00-9607-11ea-8993-f32599b98745.png">
<img width="238" alt="Capture d’écran 2020-05-14 à 17 21 24" src="https://user-images.githubusercontent.com/65354126/81959547-89429100-9607-11ea-8b72-bd5a51b4a3d9.png">

**Acceptance criteria**
Tapping on "share with anyone" opens the pop up
The default choice is "Anyone"

**Comment by devarshjoshi** [comment]
@hkellaway this is in user acceptance testing but its closed?

**Comment by haidalinda** [comment]
@devarshjoshi yes - when a task is done, the Issue is closed (so newcomers don’t think it’s work to be picked up). the card will still exist on the Project Board

**Comment by devarshjoshi** [comment]
Thanks, the milestone board looks like there are no cards for it once the
issue is closed. Something to discuss later.
Thank you,
Devarsh Joshi.

**Comment by haidalinda** [comment]
@devarshjoshi thats a good thing! a PMs objective would be to close a Milestone

**Comment by devarshjoshi** [comment]
Figured it out. The tickets that were closed didn't have the milestone to
it so it showed 0 tickets closed and 0 open.
