### ISSUE TITLE
post creation - success 

### ISSUE THREAD

**Issue by helenebar** [FightPandemics/FightPandemics-iOS#64]
**AS** a user,
**Given** that I am on the "create a post" page
**And given** that I filled in all the information and selected all relevant fields 
**When** I tap on "Post" 
**Then** a pop up appears with a post success message 
**When** I tap on "View post" in this pop up 
**Then** I am redirected to my live post 

**Design**
<img width="240" alt="Capture d’écran 2020-05-14 à 17 37 34" src="https://user-images.githubusercontent.com/65354126/81961003-aed09a00-9609-11ea-9747-3218ecefca6f.png">

**Acceptance criteria**
A success pop up appears when clicking on the Post button 
If missing info, error messages should appear

**Comment by devarshjoshi** [comment]
@hkellaway any reason this is assigned to me?

**Comment by haidalinda** [comment]
@devarshjoshi nope - mistake

**Comment by devarshjoshi** [comment]
@OnyekachiSamuel this has been in development for 15 days. Is there anything product can do to help with this ticket?
