### ISSUE TITLE
Filters for the feed

### ISSUE THREAD

**Issue by Samdisha** [FightPandemics/FightPandemics-iOS#66]
**As** a user who is signed in 
**Given** I am on my feed
**When** I want to sort my feed 
**Then** I should be able to do so using the filter option on the top right of the feed

Filter icon:
<img width="50" alt="Screen Shot 2020-05-14 at 18 27 12" src="https://user-images.githubusercontent.com/3345129/81992006-90ba6800-9610-11ea-86d5-230af667f9a2.png">

**Business Rules:**
1. When the user clicks on the filter icon, the filter modal pops up on the screen as shown in the mock
2. The previous screen (feed) will be greyed out as shown in the mocks 
3. Users can filter based on: 
    1. Location 
    2. From Whom 
    3. Type
4. Until the filters are chosen, the apply filters button will remain inactive

<img width="184" alt="Screen Shot 2020-05-14 at 18 22 53" src="https://user-images.githubusercontent.com/3345129/81991783-0114b980-9610-11ea-84f7-c6369bd6e042.png">

5. Once the user has applied the filters, they will have to click apply filters to confirm their changes

**Acceptance Criteria**
When the user clicks on the filter icon, the filter modal should pop up on the screen with options 
The "apply filters" button remains inactive until the user has chosen any filter option

**Comment by haidalinda** [comment]
covered by: 
* https://github.com/FightPandemics/FightPandemics-iOS/issues/99
* https://github.com/FightPandemics/FightPandemics-iOS/milestone/1
