### ISSUE TITLE
rectify design on create a post view

### ISSUE THREAD

**Issue by stavares843** [FightPandemics/FightPandemics-iOS#73]
figma vs app

<img width="974" alt="Screenshot 2020-05-15 at 17 24 19" src="https://user-images.githubusercontent.com/29093946/82073262-ea826700-96d0-11ea-859d-09a47957ebc7.png">

1 - close icon not aligned
2 - spacing between the asset and the copy 
3 - placeholder not aligned with the title

**Comment by haidalinda** [comment]
appreciate the visual QA @stavares843  !

**Comment by devarshjoshi** [comment]
@stavares843 any idea why this is an enhancement and not a bug?

**Comment by stavares843** [comment]
depends on the point of view, could be considered a bug because doesn't match the design but could also be considered a enhancement because the layout is implemented and is not with major critical designs issues to fix

**Comment by stavares843** [comment]
n1 fixed here - https://github.com/FightPandemics/FightPandemics-iOS/pull/123
