### ISSUE TITLE
Feed/Filter by Location - Zip Code Field

### ISSUE THREAD

**Issue by haidalinda** [FightPandemics/FightPandemics-iOS#91]
NOTE: This is ONLY for the zip code field portion of the UI - NOT the Location title, the - button, the Share my location, the Clear filters button, or the Apply filters button

ALSO NOTE: This does not include the functionality of actually searching for locations by zip code

* Form field with "Zip code, neighborhood or city"
* Tapping text field brings up a keyboard
* Localized

![Screen Shot 2020-05-17 at 5 34 59 PM](https://user-images.githubusercontent.com/5456481/82160678-ff8fff00-9864-11ea-8416-3b996d09607c.png)

**Comment by Mohammedks713** [comment]
**As** a user
**Given** I have selected the Zip Code field
**When** I type in a Zip Code, neighborhood, or City into the search bar
**Then** I should be presented in the search bar with the appropriate locations to choose from (if more than one) corresponding with my entry 

![image](https://user-images.githubusercontent.com/51894843/82597747-708e2a00-9b77-11ea-9aee-9b95b2211ef9.png)

**Acceptance Criteria**

- When I enter my location information manually via the Zip Code field, the app should identify my location and present me the correct location (or multiple options if more than one corresponding to field entry)
