### ISSUE TITLE
Feed/Filter by Location UI - Share Location Button

### ISSUE THREAD

**Issue by haidalinda** [FightPandemics/FightPandemics-iOS#92]
NOTE: This is ONLY for the Share Location portion of the UI - NOT the Location title, the - button, the zip code field, the Clear filters button, or the Apply filters button

ALSO NOTE: This does not include the functionality of enacting the Request Location Permissions flow

* Icon
* "Share my location". text
* Localized

Related to: https://github.com/FightPandemics/FightPandemics-iOS/issues/93
Related to: https://github.com/FightPandemics/FightPandemics-iOS/issues/94

![Screen Shot 2020-05-17 at 5 34 59 PM](https://user-images.githubusercontent.com/5456481/82160678-ff8fff00-9864-11ea-8416-3b996d09607c.png)

**Comment by devarshjoshi** [comment]
@eddyteddy3 whats the status on this?
