### ISSUE TITLE
Feed/Filter by Location UI - Request Permission Services Flow

### ISSUE THREAD

**Issue by haidalinda** [FightPandemics/FightPandemics-iOS#94]
NOTE: This is the flow triggered by #92

* Tapping Share my location triggers the Request Permissions utility (#93)

Related to: https://github.com/FightPandemics/FightPandemics-iOS/issues/92
Related to: https://github.com/FightPandemics/FightPandemics-iOS/issues/93

![Screen Shot 2020-05-17 at 5 34 59 PM](https://user-images.githubusercontent.com/5456481/82160678-ff8fff00-9864-11ea-8416-3b996d09607c.png)

**Comment by haidalinda** [comment]
@devarshjoshi - what happens if the user denies access to Location Services ?

**Comment by devarshjoshi** [comment]
@hkellaway 
Given On location permission section
when user has denied access for location to the app
then user sees a message replacing "share my location" -> location services disabled
I will work with design to come up with a design for that. is it possible to have a question mark next to "location services disabled" with information on how to enable it?
