### ISSUE TITLE
Nav Bar UI - Logo

### ISSUE THREAD

**Issue by haidalinda** [FightPandemics/FightPandemics-iOS#98]
NOTE: This story does NOT cover the Filter button

* Logo with circular icon + "FightPandemics" title

<img width="265" alt="Screen Shot 2020-05-17 at 4 24 35 PM" src="https://user-images.githubusercontent.com/5456481/82159301-39f49e80-985b-11ea-95f7-675254e98db4.png">

**Comment by lucianoschillagi** [comment]
The logo should be an image (png, for example) or drawing on iOS?
